### ISSUE TITLE
Preset not loaded when loading MOD-UI-Dexed from a snapshot

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-modgui#3]
When loading a MOD-UI setup from a **snapshot** (e.g. Dexed with a selected preset), the preset seems not to be loaded. The engine produces no sound. Going back (by encoder) and selecting the preset for Dexed "by hand" loads it and after that it works.

**Comment by jofemodo** [comment]
Hi @dcoredump !

This is not the right place for this issue. If it's not solved yet, you should open a new issue in the zynthian-ui repo,

Regards,
